feat: Implement ParselCrawler that adds support for Parsel
apify/crawlee-python pull request #348
Opened 2024-07-23 14:24 UTC by asymness

### Description

- Implemented ParselCrawler which adds support for [Parsel](https://github.com/scrapy/parsel)
- Added unit tests for ParselCrawler
- Added example in the docs for ParselCrawler usage

### Issues

- Closes: #335

### Testing

- Testing example included in the docs.

### Checklist

- [x] Changes are described in the `CHANGELOG.md`
- [x] CI passed

2024-07-23 15:23 UTC, janbuchar commented on tests/unit/parsel_crawler/test_parsel_crawler.py
> +            from crawlee.parsel_crawler import ParselCrawler
Nice trick!

2024-07-23 18:31 UTC, asymness commented on tests/unit/parsel_crawler/test_parsel_crawler.py
> +            from crawlee.parsel_crawler import ParselCrawler
Thanks! 🙌

2024-07-26 11:32 UTC, janbuchar reviewed
Nice job, thank you! Just two comments to think about.

2024-07-26 11:32 UTC, janbuchar commented on src/crawlee/parsel_crawler/types.py
> +    parsel: Selector
From a quick glance at the docs, I believe that the idiomatic name for this would be `selector`. What do you think?

2024-07-26 11:32 UTC, janbuchar commented on docs/examples/parsel-crawler.mdx
> +    EMAIL_REGEX = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
I'm conflicted about parsing e-mail addresses with regexp like this. The presented use case is cool, but there is almost certainly some mistake here.

2024-08-06 15:11 UTC, vdusek requested changes
LGTM; just docs:
- Could we add link to [Parsel](https://pypi.org/project/parsel/) library?
- Could we add API reference link to `ParselCrawler`?
- Could we mention the installation of the "parsel" extra?

2024-08-07 08:09 UTC, merged