feat: support custom profile in playwright
apify/crawlee-python pull request #410
Opened 2024-08-08 08:20 UTC by sherpya

if user_data_dir option is found in browser_option, then the launch function used is launch_persistent_context instead of launch and the user_data_dir option is passed to playwright

### Description

it makes possible to use custom user provided profile directory with playwright

### Issues

- Closes: #399

### Testing

```python
def create_crawler(profile: Path):
    browser_options = {
        'user_data_dir': profile
    }

    plugin = PlaywrightBrowserPlugin(browser_type='chromium', browser_options=browser_options)
    browser_pool = BrowserPool(plugins=[plugin])
    crawler = PlaywrightCrawler(browser_pool=browser_pool)

    return crawler
```

### Checklist

- [ ] CI passed

2024-08-08 08:43 UTC, sherpya commented
it would be better to add a Literal check for the browser with typing.get_args, but this would unify the typevar used in __init__ so I think it's better to have a new PR

2024-08-12 15:40 UTC, janbuchar commented
Hello @sherpya and thanks for the contribution! We should have time to review it next week.

2024-08-21 10:55 UTC, vdusek requested changes
Seems good, thanks! Could you please also add a test covering `launch_persistent_context` case?

2024-08-21 10:55 UTC, vdusek commented on src/crawlee/browsers/playwright_browser_plugin.py
> +            raise ValueError(f'Unsupported browser type: {self._browser_type}.')
Could we use the same error message as above?

```suggestion
            raise ValueError(f'Invalid browser type: {self._browser_type}.')
```

2024-08-21 10:55 UTC, vdusek commented on src/crawlee/browsers/playwright_browser_plugin.py
> +        launch_fn = 'launch_persistent_context' if 'user_data_dir' in self._browser_options else 'launch'
Maybe we could add a comment here explaining what's going on

```suggestion
        # Determine whether to launch browser with persistent context or not
        launch_fn = 'launch_persistent_context' if 'user_data_dir' in self._browser_options else 'launch'
```

2024-08-22 09:57 UTC, sherpya commented
Hi, I can make requested changes, perhaps I have no idea how to make a test for a similiar feature, do I just need to see if the call work? Or I may check if somehow the profile is created in the given directory

2024-08-22 10:21 UTC, janbuchar commented
> Hi, I can make requested changes, perhaps I have no idea how to make a test for a similiar feature, do I just need to see if the call work? Or I may check if somehow the profile is created in the given directory

The bare minimum would be to just run it and make sure it doesn't crash :slightly_smiling_face: But if you could make a profile directory somewhere and find a way to check that it is actually being used by the headless browser, that would be awesome!

2024-08-23 12:47 UTC, sherpya commented
Hi, I've got a problem, launch with profile returns a `BrowserContext` instead of a `Browser` and browser_controller._browser is `<BrowserContext browser=None>`, `browser_controller.is_browser_connected` fails because of missing property in `_browser`

2024-08-27 13:33 UTC, vdusek commented
The fact that [launch_persistent_context](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-persistent-context) returns a [BrowserContext](https://playwright.dev/python/docs/api/class-browsercontext) while the [launch](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch) returns a [Browser](https://playwright.dev/python/docs/api/class-browser) is a problem and our current abstraction is not designed to handle this difference. Addressing it would require deeper intervention into it, which I'm hesitant about.

Isn't there a way to extract a `Browser` instance from a `BrowserContext`? Alternatively, isn't there another approach to using a custom profile while still obtaining the `Browser` instance? I would rather go this way.

2024-08-30 14:19 UTC, closed without merging