docs: Deployment guide
apify/crawlee-python pull request #482
Opened 2024-08-30 13:49 UTC by janbuchar

Added a doc page about running crawlers on Apify using the SDK. I tested it, fixes will be required before publishing this.

2024-09-03 07:17 UTC, vdusek requested changes
It's not renderable:

```
Error: MDX compilation failed for file "/home/vdusek/Projects/crawlee-python/docs/introduction/09_running_in_cloud.mdx"
```

Also I'm afraid in MDX you need to use:
```mdx
{/* blahblah */}
```
for comments instead of:
```mdx
<!-- blahblah -->
```

2024-09-03 07:17 UTC, vdusek commented on templates/beautifulsoup/Dockerfile
> +RUN pip install -U pip setuptools \
why setuptools?

2024-09-04 12:53 UTC, janbuchar commented
Let's bring https://crawlee.dev/docs/deployment/apify-platform over too

2024-09-04 14:09 UTC, janbuchar commented
It would be useful to install git in the Dockerfile - it's small and it helps with installing python dependencies from github, which is situational, but useful.

2024-09-10 14:11 UTC, vdusek requested changes

2024-09-10 14:11 UTC, vdusek commented on docs/deployment/apify_platform.mdx
> +title: Apify Platform
AFAIK it should be "Apify platform" (platform is lower case, only Actor is uppercased). Please fix all occurrences.

2024-09-10 14:11 UTC, vdusek commented on website/sidebars.js
>                  // 'introduction/running-in-cloud',
This comment can be removed right?

2024-09-10 14:11 UTC, vdusek commented on docs/introduction/09_running_in_cloud.mdx
> +Now that you have your account set up, you will need to adjust the code a tiny bit. We will use the [Apify SDK](https://docs.apify.com/sdk/js/), which will help us to wire the Crawlee storages (like
please add API reference `RequestQueue`

2024-09-10 14:11 UTC, vdusek commented on docs/introduction/09_running_in_cloud.mdx
> +- Apify SDK, a toolkit for working with the Apify Platform. This will allow us to wire the storages (e.g. `RequestQueue` and `Dataset`) to the Apify cloud products. This will be a dependency of our p
please add API reference to `RequestQueue` and `Dataset`

2024-09-10 14:11 UTC, vdusek commented on docs/introduction/09_running_in_cloud.mdx
> +Open your `src/main.py` file, and wrap everyting in your `main` function with the `Actor` context manager. Your code should look like this:
API reference to Actor

2024-09-10 14:11 UTC, vdusek commented on docs/introduction/09_running_in_cloud.mdx
> +The `Actor` context manager works conditionally based on the environment variables, namely based on the `APIFY_IS_AT_HOME` env var, which is set to `true` on the Apify Platform. This means that your
again, missing API references - Actor and APIFY_IS_AT_HOME

2024-09-10 14:11 UTC, vdusek commented on docs/deployment/apify_platform.mdx
> +- [`Actor.set_value()`](https://docs.apify.com/sdk/python/reference/class/Actor#set_value), [`Actor.get_value()`](https://docs.apify.com/sdk/python/reference/class/Actor#get_value), [`Actor.get_input
API reference to KVS and Dataset

2024-09-10 14:11 UTC, vdusek commented on docs/deployment/apify_platform.mdx
> +The `ProxyConfiguration` class covers both Apify Proxy and custom proxy URLs so that
missing API reference

2024-09-11 10:30 UTC, merged