docs: added guide for result storages (Dataset, KeyValueStore)
apify/crawlee-python pull request #587
Opened 2024-10-12 18:54 UTC by Manish-k723

### Description

This PR adds documentation on Crawlee's result storage types, specifically the Key-Value Store and Dataset, providing usage examples and file structures for efficient data management.

- Closes: #479  

- [x] CI passed

2024-10-14 08:01 UTC, vdusek requested changes
It should be a guide for Crawlee Python, but your code samples are in JS. 

If you want to continue working on that, update the code samples to Python. Also, please use the same structure as we have in other guides ([docs/guides](https://github.com/apify/crawlee-python/tree/master/docs/guides)) - code samples are in separate files, we use links to API docs, ...

2024-10-16 10:51 UTC, Manish-k723 commented
Hi @vdusek updated the code as per requirement:
1. Made the guide for crawlee python which missed earlier.
2. updated the code structure as other guide docs have.

Pls let me know, if you see any other issues in this PR.

2024-10-19 21:21 UTC, Manish-k723 commented
Hi @vdusek pls check this PR and provide your valuable inputs on this, I am keen to work on this and contribute more to the crawlee community.

2024-10-21 11:35 UTC, vdusek commented
Hey @Manish-k723, CI checks are not passing.

2024-10-21 17:47 UTC, Manish-k723 commented
Hi @vdusek resolved the CI errors

2024-10-22 11:07 UTC, vdusek requested changes

2024-10-22 11:07 UTC, vdusek commented on docs/guides/code/result_storage_kvstore_basic.py
> +    await store.set_value(key='some-key', value={'foo': 'bar'})
Are you storing screenshot there?

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +description: How to store and retrieve data with KeyValueStore and Dataset in Crawlee
```suggestion
description: How to store and retrieve data with key-value store and dataset in Crawlee.
```

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +import RsPurgeExplicitlyExample from '!!raw-loader!./code/result_storage_purge_explicitly.py';
```suggestion
import DatasetBasicExample from '!!raw-loader!./code/result_storage_dataset_basic.py';
import KvsBasicExample from '!!raw-loader!./code/result_storage_kvs_basic.py';
import RsPurgeExplicitlyExample from '!!raw-loader!./code/result_storage_purge_explicitly.py';
```

2024-10-22 11:07 UTC, vdusek commented on docs/guides/code/result_storage_dataset_basic.py
> +import asyncio
Please rename the file to `result_storage_kvs_basic.py`.

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +</Tabs>
Why tabs if you have there only one item? That does not make sense. See how this is done in the [Request storage guide](https://crawlee.dev/python/docs/guides/request-storage).

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +</Tabs>
Why tabs if you have there only one item? That does not make sense. See how this is done in the [Request storage guide](https://crawlee.dev/python/docs/guides/request-storage).

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +</Tabs>
Why tabs if you have there only one item? That does not make sense. See how this is done in the [Request storage guide](https://crawlee.dev/python/docs/guides/request-storage).

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +Default storages are cleared before the crawler begins, unless specified otherwise. This clearing occurs as soon as we attempt to access any storage (e.g., through `Dataset.open()`) or when using a d
Identifiers are wrong. Probably just blindly copy-pasted from JS...

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +In Crawlee, datasets are represented by the Dataset class. To facilitate writing to the default dataset, Crawlee provides the `Dataset.pushData()` function.
Identifiers are wrong. Probably just blindly copy-pasted from JS...

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +In Crawlee, the key-value store is represented by the KeyValueStore class. To facilitate easy access to the default key-value store, Crawlee provides the functions `KeyValueStore.getValue()` and `Key
Identifiers are wrong. Probably just blindly copy-pasted from JS...

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +The `MemoryStorage` class manages Crawlee's storage. Throughout the crawler's execution, all data is held in memory, and it is simultaneously written to local files within their respective storage ty
Missing API docs link (all classes should be linked to the API docs).

2024-10-22 11:07 UTC, vdusek commented on docs/guides/result_storage.mdx
> +Invoking this function will clear the default results storage directories, with the exception of the `INPUT` key in the default key-value store directory. This serves as a shortcut to execute the opt
Missing API docs link (all classes should be linked to the API docs).

2024-10-29 12:36 UTC, vdusek commented on docs/guides/result_storage.mdx
> +</Tabs>
I mean, could you please add other tabs as we have for the [Request storage guide](https://crawlee.dev/python/docs/guides/request-storage)? Users should find out here how to use the result storages with crawlers.

- Basic usage
- Usage with Crawler
- Explicit usage with Crawler

2024-10-29 12:37 UTC, vdusek commented on docs/guides/result_storage.mdx
> +</Tabs>
Same as for KVS.

2024-11-02 10:00 UTC, Manish-k723 commented
Hey @vdusek updated the PR. thanks

2024-11-05 14:43 UTC, vdusek approved these changes
Thank you @Manish-k723, I did a little more "text polishment" and improved the code examples. Good job!

2024-11-05 14:45 UTC, merged