feat: Include whitelisted HTTP headers in extended_unique_key computation.
apify/crawlee-python pull request #590
Opened 2024-10-14 11:50 UTC by AkhilProto

### Description

This pull request enhances the `compute_unique_key` function in the `src/crawlee/_utils/requests.py` file to include HTTP headers in the unique key computation and adds corresponding unit tests. The most important changes include adding new parameters for headers and whitelisted headers, modifying the logic to compute the unique key, and adding tests to verify the new functionality.

Enhancements to `compute_unique_key` function:

* [`src/crawlee/_utils/requests.py`](diffhunk://#diff-3c15fd2da12b7729eb02594536c318224566fac913743ec91296f989b1d9c2edR94-R110): Added `headers` and `whitelisted_headers` parameters to the `compute_unique_key` function to include HTTP headers in the unique key computation.
* [`src/crawlee/_utils/requests.py`](diffhunk://#diff-3c15fd2da12b7729eb02594536c318224566fac913743ec91296f989b1d9c2edL120-L140): Modified the logic to compute the unique key by including whitelisted headers if provided.

### Issues

- Closes: #548 

### Testing

* [`tests/unit/_utils/test_compute_unique_key.py`](diffhunk://#diff-3f240e787e5702e07f327a6a70f9cb9961e1104fba6468aa1e2baa7befec7643R1-R18): Added unit tests to verify the new functionality of including headers in the unique key computation using `pytest`.

### Checklist

- [X] CI passed

2024-10-14 13:12 UTC, vdusek requested changes
Thanks for the contribution. Could you please update your code so that CI passes? Check [CONTRIBUTING.md](https://github.com/apify/crawlee-python/blob/master/CONTRIBUTING.md) for more information.

2024-10-15 00:43 UTC, AkhilProto commented
Sure. I'll start working on it.

2024-10-16 13:54 UTC, AkhilProto commented
Hey! Even after making the necessary changes and making sure that there is no room for errors, the CI tests keep failing.Upon closer inspection of the logs, it seems that the errors are originating from other files which I haven't touched. Any help regarding this would be appreciated.
Thanks!

2024-10-18 15:41 UTC, AkhilProto commented
Hey @vdusek.. Waiting for a review.

2024-10-21 11:28 UTC, vdusek commented
Hey @AkhilProto, CI is still not passing.

2024-10-21 16:17 UTC, AkhilProto commented
Yup! Had to put some effort in reformatting the other files too.. All checks have passed!

2024-10-22 06:12 UTC, vdusek requested changes
Could you also write some tests please?

2024-10-22 06:12 UTC, vdusek commented on website/generate_module_shortcuts.py
>      return shortcuts
Please do not touch this file.

2024-10-22 12:24 UTC, AkhilProto commented
Added a test and also reverted the changes made in 'website/generate_module_shortcuts.py'

2024-10-22 12:30 UTC, vdusek requested changes

2024-10-22 12:30 UTC, vdusek commented on src/crawlee/_utils/requests.py
> +    headers: dict[str, str] | None = None,
Could you please use [HttpHeaders](https://github.com/apify/crawlee-python/blob/v0.3.8/src/crawlee/_types.py#L43) type for headers? It should also help with the normalization.

2024-10-22 12:30 UTC, vdusek commented
> Added a test and also reverted the changes made in 'website/generate_module_shortcuts.py'

I don't see it :slightly_smiling_face:.

2024-10-22 12:44 UTC, AkhilProto commented
> > Added a test and also reverted the changes made in 'website/generate_module_shortcuts.py'
> 
> I don't see it 🙂.

I did update `test_requests.py`

2024-10-22 13:04 UTC, AkhilProto commented
mb.. i realized i had the tests saved locally :sweat_smile: ... i have done it now

2024-10-23 13:17 UTC, vdusek commented
Sorry, but I have to close it. There was another contributor who managed to solve it faster - #609.

2024-10-23 13:17 UTC, closed without merging

2024-10-23 15:02 UTC, AkhilProto commented
Fair enough.. It's been a pretty good experience tho! Thanks!