feat: Add `always_enqueue` option to bypass URL deduplication
apify/crawlee-python pull request #621
Opened 2024-10-25 11:19 UTC by Rutam21

### Description

This PR implements a new input parameter, always_enqueue, in the Request.from_url constructor. This feature allows users to bypass the request deduplication process, ensuring that each request is always enqueued and processed.

Key Changes:

- Added the always_enqueue parameter to the Request.from_url method.
- When always_enqueue is set to true, a random unique key is generated for each request, preventing it from being considered a duplicate.
- This enhancement provides users with a convenient way to enqueue requests without worrying about deduplication.

With this addition, users can seamlessly manage their requests while maintaining flexibility in their queuing strategy.

### Issues

Fixes #547 

### Testing

The modifications can be verified by making requests to the same URL. The operations should execute each time this is done without treating it as a duplicate request when `always_enqueue` is set to true.

- TODO

### Checklist

- [x] CI passed

2024-10-25 11:21 UTC, Rutam21 commented
@vdusek I have reviewed this issue and your suggestions and implemented them in this PR. Please review and suggest changes, if any. Thanks.

2024-10-28 18:16 UTC, Rutam21 commented
@vdusek I have reviewed this issue and your suggestions and implemented them in this PR. Please review and suggest changes, if any. Thanks.

cc; @janbuchar

2024-10-29 11:49 UTC, vdusek requested changes
This looks quite good, but make sure the CI passes (lint check, type check, unit tests... all are failing),

2024-10-29 11:49 UTC, vdusek commented on src/crawlee/_request.py
> +            unique_key += f'_{crypto_random_object_id()}'
```suggestion
            unique_key = f'{unique_key}_{crypto_random_object_id()}'
```

2024-10-30 00:42 UTC, Rutam21 commented
@vdusek Please run the CI checks again. I have pushed a commit to fix them all. Thanks.


cc: @souravjain540

2024-10-31 10:43 UTC, janbuchar commented on src/crawlee/_request.py
> +            always_enqueue: If set to `True`, the request will be enqueued even if it is already present in the queue.
```suggestion
            always_enqueue: If set to `True`, the request will be enqueued even if it is already present in the queue.
                Using this is not allowed when a custom `unique_key` is also provided and will result in a `ValueError`.
```

2024-10-31 10:45 UTC, janbuchar approved these changes
LGTM, thank you for your contribution!

2024-10-31 10:47 UTC, merged